import { BadRequestException, Param, PipeTransform, Query } from '@nestjs/common';
import { Transform } from 'class-transformer';
import { ValidateBy, type ValidationOptions } from 'class-validator';

/** Database primary keys: BIGSERIAL, generated by Postgres, one sequence per table. */
export type Id = bigint;

/** Positive integer without leading zeros, at most 2^53 - 1 so it survives JSON numbers exactly. */
const ID = /^[1-9]\d{0,15}$/;
const MAX = BigInt(Number.MAX_SAFE_INTEGER);

/** Parses a positive integer id from a string or number; returns undefined for anything else. */
export function parseId(value: unknown): Id | undefined {
  if (typeof value === 'bigint') return value > 0n && value <= MAX ? value : undefined;
  if (typeof value === 'number') return Number.isSafeInteger(value) && value > 0 ? BigInt(value) : undefined;
  if (typeof value !== 'string' || !ID.test(value)) return undefined;
  const id = BigInt(value);
  return id <= MAX ? id : undefined;
}

export class ParseIdPipe implements PipeTransform<unknown, Id | undefined> {
  constructor(private readonly options: { optional?: boolean } = {}) {}

  transform(value: unknown): Id | undefined {
    if (this.options.optional && (value === undefined || value === '')) return undefined;
    const id = parseId(value);
    if (id === undefined) throw new BadRequestException('Invalid id');
    return id;
  }
}

/** Route param as a validated bigint id: `@IdParam() id: Id`, `@IdParam('invoiceId') invoiceId: Id`. */
export const IdParam = (name = 'id') => Param(name, ParseIdPipe);
/** Optional query-string id: `@IdQuery('serviceId') serviceId?: Id`. */
export const IdQuery = (name: string) => Query(name, new ParseIdPipe({ optional: true }));

/** DTO field holding an id (or ids with `{ each: true }`); converts to bigint, rejects anything else. */
export function IsId(options?: ValidationOptions): PropertyDecorator {
  const convert = (v: unknown) => parseId(v) ?? v;
  const transform = Transform(({ value }) => (options?.each && Array.isArray(value) ? value.map(convert) : convert(value)));
  const validate = ValidateBy(
    { name: 'isId', validator: { validate: (v) => typeof v === 'bigint', defaultMessage: () => '$property must be a positive integer id' } },
    options,
  );
  return (target, key) => {
    transform(target, key);
    validate(target, key);
  };
}

declare global {
  interface BigInt {
    toJSON(): number;
  }
}

/** Ids leave the API (JSON, sockets, job payloads) as plain numbers; parseId guarantees they are safe integers. */
BigInt.prototype.toJSON = function toJSON(this: bigint) {
  return Number(this);
};
